#!/usr/bin/env bash
# command for intalling certbox
# note that you have to install this on your lb-01 server

sudo apt update
sudo apt install snapd
sudo apt-get remove certbot
sudo apt-get install certbot
# not befor you proceed stop your haproxy temporarily
sudo certbot certonly --standalone --preferred-challenges http --http-01-port 80 -d www.kaywuyep.tech
sudo ls /etc/letsencrypt/live/www.kaywuyep.tech
sudo mkdir -p /etc/haproxy/certs
DOMAIN='www.kaywuyep.tech' sudo -E bash -c 'cat /etc/letsencrypt/live/$DOMAIN/fullchain.pem /etc/letsencrypt/live/$DOMAIN/privkey.pem > /etc/haproxy/certs/$DOMAIN.pem'
sudo chmod -R go-rwx /etc/haproxy/certs
sudo vi /etc/haproxy/haproxy.cfg
~                                        
