#!/usr/bin/env bash

#  Bash script that transfers a file from our client to a server and accepts:
#  The path to the file to be transferred
#  The IP of the server we want to transfer the file to
#  The username scp connects with
#  The path to the SSH private key that scp uses
# Assign parameters to variables
# FILE_PATH="$1"
# SERVER_IP="$2"
# USERNAME="$3"
# SSH_KEY="$4"

if [ $# -lt 4 ]
then
  echo "Usage: "$0" PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
  scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~
fi
