#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server and accepts:
# The path to the file to be transferred
# The IP of the server we want to transfer the file to
# The username scp connects with
# The path to the SSH private key that scp uses

if [ $# -lt 4 ]; then
    echo "Usage: "$0" PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign parameters to variables
PATH_TO_FILE="$1"
IP="$2"
USERNAME="$3"
PATH_TO_SSH_KEY="$4"

# Transfer file using scp with strict host key checking disabled
scp -o StrictHostKeyChecking=no -i "$PATH_TO_SSH_KEY" "$PATH_TO_FILE" "$USERNAME@$IP:~/"
