#!/usr/bin/env bash
# automate an installation:
# Install nginx web server
sudo apt -y update
sudo apt -y upgrade
sudo apt -y install nginx
sudo ufw allow 'Nginx HTTP' #nginx should be listed on port 80

# Give the user ownership to website files for easy access
sudo chown -R "$USER":"$USER" /var/www/html #assign current user to server
sudo chmod -R 755 /var/www
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx restart
