#!/usr/bin/env bash
# automate an installation:
# Install nginx web server
sudo apt -y update
sudo apt -y install nginx
sudo ufw allow 'Nginx HTTP' #nginx should be listed on port 80

# Give the user ownership to website files for easy editing

echo "Hello World!" > /var/www/html/index.html
sudo service nginx restart
