#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting
# to another page.
sudo apt -y update
sudo apt -y install nginx
# Configure a 301 redirection for /redirect_me
sudo sed -i 's/80 default_server/80/' /etc/nginx/sites-available/default

# Configure a 301 redirection for /redirect_me
sudo sed -i '/server_name _;/a \\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n' /etc/nginx/sites-available/default > /dev/null

# Restart nginx without using systemctl
sudo service nginx restart
