#!/usr/bin/env bash
# Use ping to check connection to a specific IP

# Check if an IP address is provided as an argument
if [ -z "$1" ]; then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
# ping IP adress 5 times
	ping -c 5 "$1" 
fi
