#!/usr/bin/env bash
# service(init) must say-nginx is not running, replace any "8080" wit "80" conf
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
kill "$(pgrep 'nginx' | head -1)"
