#!/usr/bin/env bash
# a bash script that manages a process

# Path to the manage_my_process script
MANAGE_SCRIPT="./manage_my_process"

function error()
{
    echo "Usage: manage_my_process {start|stop|restart}"
}

function start()
{
    (./manage_my_process) &
    echo $$ > $MANAGE_SCRIPT
    echo "manage_py_process started"
}

function stop()
{
    pkill -f ./manage_my_process
    sudo rm $MANAGE_SCRIPT
    echo "manage_my_process stopped"
}

function restart()
{
    pkill -f ./manage_my_process
    rm $MANAGE_SCRIPT
    ./manage_my_process &
    echo $$ > $MANAGE_SCRIPT
    echo "manage_my_process restarted"
}

if [ $# -ne 1 ];
then
    error
else
    case ${1} in
    	"start")
    	    start;;
    	"restart")
    	    restart;;
    	"stop")
    	    stop;;
    	*)
    	    error;;
    esac
fi
