#!/usr/bin/env bash
# a Bash script that stops 4-to_infinity_and_beyond process.

# Check if the process is running
if pgrep -f "4-to_infinity_and_beyond" > /dev/null; then
    # Use pkill to terminate the process
    pkill -f "4-to_infinity_and_beyond"

fi
