#!/usr/bin/env bash
# Kill the process named "7-highlander"

# using -9: signal number 9, which is the SIGKILL signal.
# it terminates the process forcefully and does not give 
# the process a chance to cleanup or shutdown procedures

pkill -9 -f "7-highlander"
